name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2

        with:
            version: 10.13.1

      - uses: actions/setup-node@v4
        with:
            node-version: 20
            cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm test

